<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<RazorCompileOnBuild>true</RazorCompileOnBuild>
		<RazorCompileOnPublish>true</RazorCompileOnPublish>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IsPackable>true</IsPackable>

		<PackageId>RazorClassBlog</PackageId>
		<Title>RazorClassBlog</Title>
		<Description>Basic Razor Class Library Blog System</Description>
		<Authors>Jason Hargrave</Authors>
		<Copyright>2025</Copyright>

		<VersionPrefix>1.0.1</VersionPrefix>
		<PackageReleaseNotes>Updated to allow uploads of images to blob storage.</PackageReleaseNotes>
		
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		
		<RepositoryUrl>https://github.com/Hargravejason/RazorClassBlog</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/Hargravejason/RazorClassBlog</PackageProjectUrl>

		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>

		<PackageTags>blog;razor-pages;rcl;seo;aspnetcore;bootstrap</PackageTags>
	</PropertyGroup>
	
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.23.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
	</ItemGroup>
</Project>
